version: 2.1
executors:
  default:
    docker:
      - image: circleci/node:18.17.1
        environment:
          TZ: Asia/Tokyo
          working_directory: ~/repo/src

commands:
  restore_npm:
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "src/yarn.lock" }}
            - v1-dependencies-

  save_npm:
    steps:
      - save_cache:
          paths:
            - src/node_modules
          key: v1-dependencies-{{ checksum "src/yarn.lock" }}

  restore_node:
    steps:
      - restore_cache:
          key: node-v2-{{ checksum "src/yarn.lock" }}

  save_node:
    steps:
      - save_cache:
          key: node-v2-{{ checksum "src/yarn.lock" }}
          paths:
            - src/node_modules

jobs:
  node:
    executor:
      name: default
    steps:
      - checkout
      - restore_npm
      - save_npm
      - run: cd src && yarn install
      - restore_node
      - save_node

  lint:
    executor:
      name: default
    steps:
      - checkout
      - restore_npm
      - save_npm
      - run: cd src && yarn install
      - run: cd src && npm run lint

workflows:
  version: 2
  build_and_test:
    jobs:
      - node:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - lint:
          requires:
            - node
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
