version: 2.1

orbs:
  node: circleci/node@4.7.0

jobs:
  install_dependencies:
    docker:
      - image: cimg/node:18.18
    steps:
      - checkout
      - run:
          name: "Install pnpm"
          command: "sudo npm install -g pnpm"
      - run:
          name: "Install Dependencies"
          command: |
            cd src &&
            pnpm install
      - save_cache:
          key: v1-dependencies-{{ checksum "src/package.json" }}
          paths:
            - src/node_modules

  build:
    docker:
      - image: cimg/node:18.18
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "src/package.json" }}
      - run:
          name: "Run Build"
          command: |
            cd src &&
            pnpm run build

  test:
    docker:
      - image: cimg/node:18.18
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "src/package.json" }}
      - run:
          name: "Run Tests"
          command: |
            cd src &&
            pnpm run test

workflows:
  version: 2
  build-and-test:
    jobs:
      - install_dependencies
      - build:
          requires:
            - install_dependencies
      - test:
          requires:
            - install_dependencies
