version: 2.1

orbs:
  node: circleci/node@4.7.0

jobs:
  install_dependencies:
    docker:
      - image: cimg/node:18.18
    steps:
      - checkout
      - run:
          name: Install pnpm
          command: sudo npm install -g pnpm --unsafe-perm=true --allow-root

  run_tests:
    docker:
      - image: cimg/node:18.18
    steps:
      - checkout
      - run:
          name: "Install Dependencies and Run Tests"
          command: |
            cd src &&
            sudo npm install -g pnpm &&
            pnpm run test

  build_application:
    docker:
      - image: cimg/node:18.18
    steps:
      - checkout
      - run:
          name: "Install Dependencies with pnpm"
          command: sudo pnpm install --unsafe-perm=true --allow-root
      - run:
          name: "Build Application"
          command: pnpm run build

workflows:
  version: 2
  build-and-test:
    jobs:
      - install_dependencies
      - run_tests:
          requires:
            - install_dependencies
      - build_application:
          requires:
            - run_tests
