version: 2.1

orbs:
  node: circleci/node@4.7.0

jobs:
  install_dependencies:
    docker:
      - image: cimg/node:18.18
    steps:
      - checkout
      - run:
          name: Install pnpm and Dependencies
          command: |
            cd src &&
            sudo npm install -g pnpm

  build_application:
    docker:
      - image: cimg/node:18.18
    steps:
      - checkout
      - run:
          name: "Build Application"
          command: |
            cd src &&
            pnpm run build

workflows:
  version: 2
  build-and-test:
    jobs:
      - install_dependencies
      - build_application:
          requires:
            - install_dependencies
