version: 2.1

orbs:
  node: circleci/node@4.7.0

jobs:
  install_dependencies:
    docker:
      - image: cimg/node:18.18
    steps:
      - checkout
      - run:
          name: Install pnpm
          command: sudo npm install -g pnpm

  build_application:
    docker:
      - image: cimg/node:18.18
    steps:
      - checkout
      - run:
          name: "Install Dependencies with pnpm"
          command: sudo pnpm install
      - run:
          name: "Build Application"
          command: pnpm run build

workflows:
  version: 2
  build-and-test:
    jobs:
      - install_dependencies
      - build_application:
          requires:
            - run_tests
