version: 2.1
executors:
  default:
    docker:
      - image: circleci/node:16.8.0
        environment:
          TZ: Asia/Tokyo
          working_directory: ~/repo/src

commands:
  restore_npm:
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "src/package-lock.json" }}
            - v1-dependencies-

  save_npm:
    steps:
      - save_cache:
          paths:
            - src/node_modules
          key: v1-dependencies-{{ checksum "src/package-lock.json" }}

  restore_node:
    steps:
      - restore_cache:
          key: node-v2-{{ checksum "src/package-lock.json" }}

  save_node:
    steps:
      - save_cache:
          key: node-v2-{{ checksum "src/package-lock.json" }}
          paths:
            - src/node_modules

jobs:
  node:
    executor:
      name: default
    steps:
      - checkout
      - restore_npm
      - save_npm
      - run: cd src && npm install
      - restore_node
      - save_node

workflows:
  version: 2
  build_and_test:
    jobs:
      - node:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - lint:
          executor:
            name: default
          steps:
            - checkout
            - restore_npm
            - save_npm
            - run: cd src && npm install
            - run: cd src && npm run lint
      - test:
          requires:
            - node
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - build:
          requires:
            - lint
            - test
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
